UNIT 3 Lesson 1 - NumPy

https://colab.research.google.com/drive/1qiFRfkTIgum8HxfejX6MOqknMO7dWyBO?usp=sharing#scrollTo=9Oek0G2ykcEb

In [ ]:
#NUMPY 
#Attributes of ndarray (N-dimensional arrays) Object 
import numpy as np 
a = np.array([1,2,3, 9], dtype='int32')
print(a)

#dtype = data type 


[1 2 3 9]


In [ ]:
#Attributes of ndarray object 
#ndarray.ndim
#Get Dimension 
a.Ndim 

#Gete num of elements in each array 
a.shape
(3,)
# or (3,2) 3 rows 2 column 

#Get number of elements 
a. Size 
3

#Get Type 
a. dtype 
dtype('int32')

NameError: ignored

In [ ]:
a = np.array([1,2,3])
print(a)

NameError: ignored

In [ ]:
import numpy as np
a = np.array([1,2,3,9], dtype='int32')
print(a)

[1 2 3 9]


In [ ]:
import numpy as np
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)
print(b.size)
b.shape

[[9. 8. 7.]
 [6. 5. 4.]]
6


(2, 3)

In [ ]:
b.ndim

2

In [ ]:
#Get Dimension 
a.ndim 

1

In [ ]:
a.shape

#Professor got (4,)

(3,)

In [ ]:
#Get Size
a.itemsize

4

In [ ]:
import numpy as np 
c = np.array([13,2,3,9], dtype='int32')
print(c)
#c.itemsize
c.size

[13  2  3  9]


4

In [ ]:
cars = np.array(['dodge', 'jeep', 'bmw'], dtype=str)
print(cars)

['dodge' 'jeep' 'bmw']


In [ ]:
cars.shape

(3,)

In [ ]:
cars.size

3

In [ ]:
cars.ndim

1

In [ ]:
cars.itemsize

20

In [ ]:
cars.dtype
#data says unified 5 meaning it's a string

dtype('<U5')

In [ ]:
#TRYMYSELF 
food = np.array(['cupcake', 'sushi', 'mochi'])
print(food)

['cupcake' 'sushi' 'mochi']


Accessing/Changing specific elements row, columns, etc

In [ ]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a[1,0], a[1,2])

#[1,0] means row 1 in previous printed out list and the 0 element
#[1,2] means row 2 in previous print and the 2nd element so 10 

8 10


In [ ]:
#Get a specific element [r,c]
a[1,5]

13

In [ ]:
#Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
#Get a specific column 
a[:,2]

array([ 3, 10])

Initializing Different Types of Arrays

In [ ]:
#All 0s matrix 
np.zeros((2,3))
#meaning 2 rows and 3 columns filled with 0s

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#All is matrix 
d=np.ones((4,2), dtype='int32')
d

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

Mathematics/can peform basic +,-,/,* and advanced operations

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
array([3,4,5,6])

NameError: ignored

In [ ]:
a*2

array([2, 4, 6, 8])

In [ ]:
#adding two arrays, is adding each element by element 
a = np.array([1,2,3,4])
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

Accessing Elements of Array

In [ ]:
a = np.array([17,2,3,4])
print(a[0])
a[3]

17


4

In [ ]:
w=np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(w)
print(w[0,0])
print(w[1,3])

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
1
11


In [ ]:
import numpy as np 
arr = np.array([1,2,3,4])
print(arr[2] + arr[3])

7


***Finding value greater or less < x > in Array ** Assignment 

In [ ]:
import numpy as np 
studentscore= np.array([56,87,43,68,90])
passingscore=studentscore > 60
print(passingscore)
studentscore[passingscore]

[False  True False  True  True]


array([87, 68, 90])

In [ ]:
#TRYMYSELF
import numpy as np 
favoritenumbers = np.array([7,13,27,77])
numbers=favoritenumbers > 7
print(numbers)
favoritenumbers[numbers]

[False  True  True  True]


array([13, 27, 77])

In [ ]:
import numpy as np
cars = np.array(['dodge', 'jeep', 'bmw'])
print(cars)
autos=cars
print(autos)
#show both subjects are the same 
print(cars is autos)
print(len (autos))
autos[1]='benz' #forcing first element to be benz so change from jeep to benz
print(autos)
print(cars)

['dodge' 'jeep' 'bmw']
['dodge' 'jeep' 'bmw']
True
3
['dodge' 'benz' 'bmw']
['dodge' 'benz' 'bmw']


Some times we want to manipulate an array but keep a copy of older version

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42 #means take the 0 element or 1st number and change from 1 to 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


(Ufunc) Universal functions, ufuncs stands for "Universal Functions" and they are NumPy functions that operate on the ndarray object.

In [ ]:
import numpy as np 
x = [1,2,3,4]
y = [4,5,6,7]
z = np.add(x,y)

print(z)

[ 5  7  9 11]


In [ ]:
#TRYMYSELF
import numpy as np 
x = [2,4,5,8]
y = [2,2,2,2]
z = np.multiply(x,y)

print(z)

[ 4  8 10 16]


In [ ]:
import numpy as np

arr1 = np.array([10,11,12,13,14,15])
arr2 = np.array([20,21,22,23,24,25])

newarr = np.add(arr1, arr2)
print(newarr)
newarr=arr1-arr2
newarr
print(newarr)

[30 32 34 36 38 40]
[-10 -10 -10 -10 -10 -10]


In [ ]:
import numpy as np 

arr1 = ([10,11,45,180,90,0])
print(np.cos(arr1))
print(np.sqrt(arr1))

[-0.83907153  0.0044257   0.52532199 -0.59846007 -0.44807362  1.        ]
[ 3.16227766  3.31662479  6.70820393 13.41640786  9.48683298  0.        ]


Transposing array

In [ ]:
import numpy as np
ary = np.array([1,2,3], [4,5,6])
print(ary)
np.transpose(ary)
print(np.transpose(ary))

TypeError: ignored

Statistics on Arrays

**Finding min, max values in Array** Assignment

In [ ]:
#Find Max number in Array 
score = np.array([[1,2,3], [4,5,6]])
score

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(np.min(score))
print(np.max(score))

1
6


Assignment Unit_2, L1: Find maximum value and its index in a 1D NumPy Array:

In [ ]:
#Find max value & its index in a 1D NumPy Array: 
import numpy as np
num = np.array([11,12,13,14,15,16,17,15,11,12,14,15,16,17])
print(np.max(num))

17


Find index of maximum value: Get the array of indices/indexes of maximum value in NumPy array using numpy.where() *italicized_text*

In [ ]:
# Get the max and indices of maximum element in numpy array
import numpy as np
num = np.array([11, 12, 13, 14, 15, 16, 17, 15, 11, 12, 14, 15, 16, 17])
result = np.where(num == np.max(num)) #create variable which will have the value of the max element in array (num in this case)
print('return max value',np.max(num))
print('Returned tuple of arrays :', result) # 
print('List of Indices of maximum element :', result[0])#,result[0] is the variable where [0] indicates where in the array the max value is

return max value 17
Returned tuple of arrays : (array([ 6, 13]),)
List of Indices of maximum element : [ 6 13]


In [ ]:
#Dataset from summer Olympic London, year 2012
import numpy as np
np_olympic_country = np.array(['GBR','China','RUS','US','KOR','JPN','GER'])
np_olympic_country_Gold = np.array([29,38,24,46,13,7,11])
np_olympic_country_Silver = np.array([17,28,25,28,8,14,11])
np_olympic_country_Bronze = np.array([19,22,32,29,7,17,14])
highest = np.where(np_olympic_country_Gold== np.max(np_olympic_country_Gold))
print('Max number of gold medals',np.max(np_olympic_country_Gold ))
print('index number of maximum element (gold medals) :', highest[0])
print('The country with Max number of gold medals is:',np_olympic_country[highest])
more_than_20_medals=np_olympic_country_Gold >20
print(more_than_20_medals)
np_olympic_country_Gold[more_than_20_medals]
x = np.where(np_olympic_country_Gold >20)

print('the countrieas with more than 20 medals are:',np_olympic_country[x])

Max number of gold medals 46
index number of maximum element (gold medals) : [3]
The country with Max number of gold medals is: ['US']
[ True  True  True  True False False False]
the countrieas with more than 20 medals are: ['GBR' 'China' 'RUS' 'US']


If you have confusion, try to change any number from the list, such as 7 to 46, so in result you will get US and JPN
-Rabiul

I change the list that way: np_olympic_country_Gold = np.array([29,38,24,46,13,46,11])

highest[0] is tuple index, which is 0, if you change any other number it will give you error that said tuple out of range.

-Rabiul

In [ ]:
#Find countrieas with more than 20 gold metals
import numpy as np
np_olympic_country_Gold = np.array([29,38,24,46,13,7,11])
more_than_20_medals=np_olympic_country_Gold >20
print(more_than_20_medals)
np_olympic_country_Gold[more_than_20_medals]
x = np.where(np_olympic_country_Gold >20)

print(x)

[ True  True  True  True False False False]
(array([0, 1, 2, 3]),)


UNIT 3 Lesson 2 - PANDAS

https://colab.research.google.com/drive/1KoKg5VJjgu5SrEXt5Hpua64U_veKojxY?usp=sharing

Pandas is a Python library used for working with data sets. 
It has functions for analyzing, cleaning, exploring, and manipulating data. 
The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis"

Pandas gives you answers about data.
1. Is there a correlation between two or more columns?
2. What is average? 
3. and more....

Series in Pandas 
-A series is like a column in a table. 
-It is a one-dimensional array holding data of any types. Series are part of DataFrames.
  -a dataframe is a collection of series. 

-DataFrame is a 2-dimensional labeled data structure with columns of potentially different types. You can think of it like a spreadsheet or SQL table, or a dictionary of Series objects.

day 1    420
day 2    380 
day 3    390 
dtype: int64 

In [ ]:
day 1    420
day 2    380 
day 3    390 
dtype: int64 #output

In [ ]:
#EXAMPLE 
#Create a simple Pandas Series from a dictionary: 
import pandas as pd 

calories= {"day1": 420, "day2":380, "day3": 390}

myvar = pd.Series(calories)

print(myvar)

day1    420
day2    380
day3    390
dtype: int64


In [ ]:
#A Pandas DataFrame is a 2-dimensional data structure
#like a 2-dimensional array, or a table with rows and columns

#Create a simple Pandas DataFrame:
import pandas as pd 

data = {
    "calories": [420,380,390],
    "duration": [50,40,45]
}

#load data into a DataFrame object: 
df = pd.DataFrame(data)

print(df)

   calories  duration
0       420        50
1       380        40
2       390        45


In [ ]:
#DATAFRAMES 

import numpy as np 
import pandas as pd 
rows = ['x', 'y',  'z', 'W']
coloms = ['1', '2', '3', '4']
df = pd.DataFrame(np.random.randint(0,10, size=(4,4)), columns=coloms, index=rows)
df

#random integer 

1  2  3  4
x  1  5  4  2
y  5  7  5  5
z  6  2  7  0
W  0  8  4  4

In [ ]:
import numpy as np 
import pandas as pd 
rows = ['x', 'y',  'z', 'W']
coloms = ['1', '2', '3', '4']
df = pd.DataFrame(np.random.randint(0,10, size=(4,4)), columns=coloms, index=rows)
print(df)
df['new']=df['1']
print('=========++++++++++')
print(df)
#To select multiple columns 
df[['1', '2']]

   1  2  3  4
x  2  6  6  5
y  0  0  3  9
z  4  8  2  4
W  8  9  0  7
=========++++++++++
   1  2  3  4  new
x  2  6  6  5    2
y  0  0  3  9    0
z  4  8  2  4    4
W  8  9  0  7    8


1  2
x  2  6
y  0  0
z  4  8
W  8  9

In [ ]:
#How to Drop New Column 
#del df['column_name']
del df['three'] #three should be an actual number "3"

In [ ]:
import numpy as np 
import pandas as pd 
rows = ['x', 'y',  'z', 'W']
coloms = ['1', '2', '3', '4']
df = pd.DataFrame(np.random.randint(0,10, size=(4,4)), columns=coloms, index=rows)
print(df)
df['new']=df['1']
print('=========++++++++++')
print(df)
#To select multiple columns 
df[['1', '2']]
del df['3']

   1  2  3  4
x  1  4  8  4
y  1  2  3  9
z  1  2  4  9
W  6  1  1  6
=========++++++++++
   1  2  3  4  new
x  1  4  8  4    1
y  1  2  3  9    1
z  1  2  4  9    1
W  6  1  1  6    6


Data Frames 
-We can create new dataframes by assigning our subset to a new varibale, for instance: 

In [ ]:
#df2 = df[['W', 'X']]
#-Our new dataframe (df2) will only have those columns 

#create new data frame using existing one 
df2=df[['1', 'new']]
print('==========+++++++++++')
print(df2)

#Dropping rows 
print(df2.drop('y'))

==========+++++++++++
   1  new
x  1    1
y  1    1
z  1    1
W  6    6
   1  new
x  1    1
z  1    1
W  6    6


SELECTING ROWS
-use loc and iloc to select rows

Actually from here to when I signal stop, the PPT is from an old version so I'll redo it to match the new version which is what is on Google Classroom
----------------------------------------

In [ ]:
#based on tables shown in PPT 
df.loc['C']
df.iloc[2]

KeyError: ignored

In [ ]:
#FILTERING 
#again, he has a table in PPT that has w,x,y,z that I don't know how he got 
#also has true, false,...

df > 0 #so basically using the table he has, he put if df>0 : give back
      #true or false 

We can save this as a variable: booldf = df > 0 
When we run 'booldf', we'll get the same output 

booldf = df > 0 
booldf 
--> show the data of true vs false 

If we pass booldf into our original df 
We can see the values where it was True 
df[booldf]
--> Look at PPT Unit3 L2 Ppandass slide 12 and you'll see NaN'
NaN means not a number 

---------------------------------------
STOP HERE - the old presentation

Unit 3 L2 Pandas Slide 10
DATA FRAMES - COLUMNS

In [ ]:
#To select multiple columns, we pass in a list of column names 
df[['W','X']]

#We can create new columns in our data frame as well - as if they already exist 
df['new'] = df['W'] + df['Y']
df

#df.drop('new', axis=l, inplace = True) will drop the column from the dataframe
-Axis=l tells Python to look at the columns. If you specifiy axis = 0, 
you will be removing rows from the dataset. 
-Inplace = True tells Python to modify the existing dataframe - 
why might this be important?

KeyError: ignored

In [ ]:
#DATA FRAMES 
-We can create new dataframes by assigning our subset to a new variable
for instance: 

df2 = df[['W', 'X']] 
**finish up in slide 11

In [ ]:
#SELECTING ROWS 
#we use loc and iloc to select rows 

df.loc['C']
df.iloc[2]
#iloc = integer index based 
#Integer Loc 

KeyError: ignored

FILTERING Slides 13-15

RENAMING COLUMNS

In [ ]:
df = df.rename(columns={'Unnamed: 0': 'newName1', 'oldName2':'newName2'})
#Or rename the existing DataFrame (rather than creating a copy)
df.rename(columns={'oldName1': 'newName1', 'oldName2':'newName2'}, inplace=True)

In [ ]:
import pandas as pd 

data = {
    "age": [50,40,30],
    "qualified": [True, False, False]
}
idx = ["Sally", "Mary", "John"]
df = pd.DataFrame(data, index=idx)

newdf = df.rename({"Sally": "Pete", "Mary": "Patrick"})
print(df)
print("--------------------")
print(newdf)

       age  qualified
Sally   50       True
Mary    40      False
John    30      False
--------------------
         age  qualified
Pete      50       True
Patrick   40      False
John      30      False


In [ ]:
#IN YOUR NOTEBOOK: 
#-Installing and loading these packages into your NB
!pip install pandas 
!pip install matplotlib 

import pandas as pd 
import matplotlib.pyplot as plt 

In [ ]:
#1st - import data into our NB 
#open the Co-Lab link 
https://colab.research.google.com/drive/1KoKg5VJjgu5SrEXt5Hpua64U_veKojxY?usp=sharing#scrollTo=bQDaCXnqYKCg

https://colab.research.google.com/drive/1KoKg5VJjgu5SrEXt5Hpua64U_veKojxY?usp=sharing#scrollTo=bQDaCXnqYKCg